[package]
name = "mindmesh-frontend"
version = "1.0.0"
edition = "2021"

[dependencies]
mindmesh-core = { path = "../core" }
iced = { version = "0.12", features = ["canvas", "tokio"] }
rand = "0.8"
serde_json = "1.0"
chrono = "0.4"
rodio = "0.17"
serialport = "4.2"
image = "0.24"
